controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Primer rutiranja iz routes.yaml:
# app_index:
#     path: /
#     controller: App\Controller\HelloController::index